# Generated by Django 5.2.17 on 2026-09-27 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("authentication", "0026_alter_characterownership_user_and_more"),
        ("esi", "0013_squashed_0012_fix_token_type_choices"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Killmail",
            fields=[
                (
                    "id",
                    models.PositiveBigIntegerField(primary_key=True, serialize=False),
                ),
                ("hash", models.CharField(max_length=40)),
                ("occurred_at", models.DateTimeField(db_index=True)),
                ("solar_system_id", models.PositiveBigIntegerField()),
                ("victim_character_id", models.PositiveBigIntegerField(null=True)),
                ("victim_corporation_id", models.PositiveBigIntegerField(null=True)),
                ("victim_alliance_id", models.PositiveBigIntegerField(null=True)),
                ("victim_ship_type_id", models.PositiveBigIntegerField()),
            ],
            options={
                "ordering": ["-occurred_at", "-id"],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "killmail_id",
                    models.PositiveBigIntegerField(primary_key=True, serialize=False),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("sending", "Sending"),
                            ("submitted", "Pushed"),
                            ("rejected", "Rejected — retry available"),
                            ("unknown", "Outcome unknown — push locked"),
                        ],
                        db_index=True,
                        default="sending",
                        max_length=12,
                    ),
                ),
                ("attempted_at", models.DateTimeField()),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("message", models.CharField(blank=True, max_length=160)),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "default_permissions": ("view",),
            },
        ),
        migrations.CreateModel(
            name="TrackedCharacter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owner_hash", models.CharField(max_length=254)),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
                (
                    "next_poll",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("next_page", models.PositiveIntegerField(default=1)),
                ("sync_lock", models.UUIDField(blank=True, null=True)),
                ("lock_until", models.DateTimeField(blank=True, null=True)),
                ("error", models.CharField(blank=True, max_length=160)),
                (
                    "ownership",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="killpusher_character",
                        to="authentication.characterownership",
                    ),
                ),
                (
                    "token",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="esi.token",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": [("basic_access", "Can use Killmail Pusher")],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="CharacterKillmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(choices=[("kill", "Kill"), ("loss", "Loss")], max_length=4),
                ),
                (
                    "killmail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="involvements",
                        to="killpusher.killmail",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="killpusher.trackedcharacter",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("character", "killmail"), name="kp_character_kill"
                    )
                ],
            },
        ),
    ]
