# Generated by Django 5.2.17 on 2026-09-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("killpusher", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="killmail",
            name="next_name_check",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="killmail",
            name="next_public_check",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="killmail",
            name="victim_character_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="killmail",
            name="victim_corporation_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
